### ISSUE TITLE
enabling ssl enforces the use of ssl_cert with no error handling

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-output-tcp#22]
If ssl is enabled, the plugin assumes `ssl_cert` is enabled and [crashes trying to read a nil path](https://github.com/logstash-plugins/logstash-output-tcp/blob/v4.0.0/lib/logstash/outputs/tcp.rb#L94):

config:

```
input {
    stdin {}
}
output {
    tcp {
        host => "localhost"
        port => 9000
        ssl_cacert => "/Users/jared/tmp/pki/certs/carey_ca.cert.pem"
        ssl_enable => true
        ssl_verify => false
    }
}
```

output:

```
[2016-09-23T10:58:15,789][ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<TypeError: can't convert nil into String>, :backtrace=>["org/jruby/RubyIO.java:3804:in `read'", "org/jruby/RubyIO.java:3987:in `read'", "/Users/jared/builds/logstash/logstash-5.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-output-tcp-4.0.0/lib/logstash/outputs/tcp.rb:94:in `setup_ssl'", "/Users/jared/builds/logstash/logstash-5.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-output-tcp-4.0.0/lib/logstash/outputs/tcp.rb:115:in `register'", "/Users/jared/builds/logstash/logstash-5.0.0-beta1/logstash-core/lib/logstash/output_delegator_strategies/single.rb:9:in `register'", "/Users/jared/builds/logstash/logstash-5.0.0-beta1/logstash-core/lib/logstash/output_delegator.rb:37:in `register'", "/Users/jared/builds/logstash/logstash-5.0.0-beta1/logstash-core/lib/logstash/pipeline.rb:196:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/Users/jared/builds/logstash/logstash-5.0.0-beta1/logstash-core/lib/logstash/pipeline.rb:196:in `start_workers'", "/Users/jared/builds/logstash/logstash-5.0.0-beta1/logstash-core/lib/logstash/pipeline.rb:153:in `run'", "/Users/jared/builds/logstash/logstash-5.0.0-beta1/logstash-core/lib/logstash/agent.rb:250:in `start_pipeline'"]}
```

**Comment by ctindel** [comment]
@jsvd do we plan to merge this PR any time soon?

https://github.com/logstash-plugins/logstash-output-tcp/pull/31

One of my commercial users is asking.
